const int ledVerde1 = 8;
 const int ledRosu = 10;
 const int ledVerde2 = 12; 
 const int ledGalben = 13;
const int ledRosu1 = 7;
const int ledGalben1 = 6;
void setup(){
pinMode(ledVerde1, OUTPUT);
pinMode(ledRosu, OUTPUT);
pinMode(ledVerde2, OUTPUT);
pinMode(ledGalben, OUTPUT);
pinMode(ledRosu1, OUTPUT);
pinMode(ledGalben1, OUTPUT);
randomSeed(analogRead(0));

}
void loop(){
 digitalWrite(ledVerde1, HIGH);
 delay(200);
 digitalWrite(ledRosu, HIGH);
  delay(200);
 digitalWrite(ledVerde2,  HIGH);
  delay(200);
 digitalWrite(ledGalben, HIGH); 
  delay(200);
  digitalWrite(ledRosu1, HIGH); 
  delay(200);
  digitalWrite(ledGalben1, HIGH); 
  delay(200);
 digitalWrite(ledVerde1, LOW);
 delay(200);
 digitalWrite(ledRosu, LOW);
  delay(200);
 digitalWrite(ledVerde2,  LOW);
  delay(200);
 digitalWrite(ledGalben, LOW); 
  delay(200);
  digitalWrite(ledRosu1, LOW); 
  delay(200);
    digitalWrite(ledGalben1, LOW); 
  delay(200);

digitalWrite(ledVerde1, HIGH);
 delay(200);
 digitalWrite(ledVerde2,  HIGH);
  delay(200);
  digitalWrite(ledVerde1, LOW);
 delay(200);
 digitalWrite(ledVerde2,  LOW);
  delay(200);
  digitalWrite(ledRosu, HIGH);
  delay(200);
  digitalWrite(ledGalben, HIGH); 
  delay(200);
  digitalWrite(ledRosu, LOW);
  delay(200);
  digitalWrite(ledGalben, LOW); 
  delay(200);

digitalWrite(ledRosu, HIGH);
  delay(200);
digitalWrite(ledGalben, HIGH); 
  delay(200);
digitalWrite(ledVerde2,  HIGH);
  delay(200);
  digitalWrite(ledRosu, LOW);
  delay(200);
  digitalWrite(ledGalben, LOW); 
  delay(200);
  digitalWrite(ledVerde2,  LOW);
  delay(200);

digitalWrite(ledVerde1, HIGH);
 digitalWrite(ledRosu, HIGH); 
 digitalWrite(ledVerde2,  HIGH);
 digitalWrite(ledGalben, HIGH);
 delay(50); 
 digitalWrite(ledVerde1, LOW);
 digitalWrite(ledRosu, LOW);
 digitalWrite(ledVerde2,  LOW);
 digitalWrite(ledGalben, LOW); 
  delay(50); 
digitalWrite(ledVerde1, HIGH);
 digitalWrite(ledRosu, HIGH); 
 digitalWrite(ledVerde2,  HIGH);
 digitalWrite(ledGalben, HIGH);
 delay(50); 
 digitalWrite(ledVerde1, LOW);
 digitalWrite(ledRosu, LOW);
 digitalWrite(ledVerde2,  LOW);
 digitalWrite(ledGalben, LOW); 
  delay(50); 
 digitalWrite(ledVerde1, HIGH);
 digitalWrite(ledRosu, HIGH); 
 digitalWrite(ledVerde2,  HIGH);
 digitalWrite(ledGalben, HIGH);
 delay(50); 
 digitalWrite(ledVerde1, LOW);
 digitalWrite(ledRosu, LOW);
 digitalWrite(ledVerde2,  LOW);
 digitalWrite(ledGalben, LOW); 
  delay(50); 
 digitalWrite(ledVerde1, HIGH);
 digitalWrite(ledRosu, HIGH); 
 digitalWrite(ledVerde2,  HIGH);
 digitalWrite(ledGalben, HIGH);
 delay(50); 
 digitalWrite(ledVerde1, LOW);
 digitalWrite(ledRosu, LOW);
 digitalWrite(ledVerde2,  LOW);
 digitalWrite(ledGalben, LOW); 
  delay(50); 

 digitalWrite(ledVerde1, HIGH);
 digitalWrite(ledRosu, HIGH); 
 digitalWrite(ledVerde2,  HIGH);
 digitalWrite(ledGalben, HIGH);
 digitalWrite(ledRosu1, HIGH); 
 digitalWrite(ledGalben1, HIGH); 
 delay(50); 
 digitalWrite(ledVerde1, LOW);
 digitalWrite(ledRosu, LOW);
 digitalWrite(ledVerde2,  LOW);
 digitalWrite(ledGalben, LOW); 
 digitalWrite(ledRosu1, LOW); 
 digitalWrite(ledGalben1, LOW); 
  delay(50); 
digitalWrite(ledVerde1, HIGH);
 digitalWrite(ledRosu, HIGH); 
 digitalWrite(ledVerde2,  HIGH);
 digitalWrite(ledGalben, HIGH);
 digitalWrite(ledRosu1, HIGH); 
 digitalWrite(ledGalben1, HIGH); 
 delay(50); 
 digitalWrite(ledVerde1, LOW);
 digitalWrite(ledRosu, LOW);
 digitalWrite(ledVerde2,  LOW);
 digitalWrite(ledGalben, LOW);
 digitalWrite(ledRosu1, LOW);  
 digitalWrite(ledGalben1, LOW); 
  delay(50); 
 digitalWrite(ledVerde1, HIGH);
 digitalWrite(ledRosu, HIGH); 
 digitalWrite(ledVerde2,  HIGH);
 digitalWrite(ledGalben, HIGH);
 digitalWrite(ledRosu1, HIGH); 
 digitalWrite(ledGalben1, HIGH); 
 delay(50); 
 digitalWrite(ledVerde1, LOW);
 digitalWrite(ledRosu, LOW);
 digitalWrite(ledVerde2,  LOW);
 digitalWrite(ledGalben, LOW); 
  digitalWrite(ledRosu1, LOW); 
  digitalWrite(ledGalben1, LOW); 
  delay(50); 
 digitalWrite(ledVerde1, HIGH);
 digitalWrite(ledRosu, HIGH); 
 digitalWrite(ledVerde2,  HIGH);
 digitalWrite(ledGalben, HIGH);
  digitalWrite(ledRosu1, HIGH); 
  digitalWrite(ledGalben1, HIGH); 
 delay(50); 
 digitalWrite(ledVerde1, LOW);
 digitalWrite(ledRosu, LOW);
 digitalWrite(ledVerde2,  LOW);
 digitalWrite(ledGalben, LOW); 
  digitalWrite(ledRosu1, LOW); 
  digitalWrite(ledGalben1,LOW); 
  delay(50); 
  for(int i=0;i<=5;i++){
  int ledAleator =random (6);
  if(ledAleator == 0) digitalWrite(ledVerde1, HIGH);
  if(ledAleator == 1) digitalWrite(ledRosu, HIGH);
  if(ledAleator == 2) digitalWrite(ledVerde2, HIGH);
  if(ledAleator == 3) digitalWrite(ledGalben, HIGH);
  if(ledAleator == 4) digitalWrite(ledRosu1, HIGH);
  if(ledAleator == 5) digitalWrite(ledGalben1, HIGH);
  delay(200);
 if(ledAleator == 0) digitalWrite(ledVerde1, LOW);
  if(ledAleator == 1) digitalWrite(ledRosu,LOW);
  if(ledAleator == 2) digitalWrite(ledVerde2, LOW);
  if(ledAleator == 3) digitalWrite(ledGalben, LOW);
  if(ledAleator == 4) digitalWrite(ledRosu1, LOW);
  if(ledAleator == 5) digitalWrite(ledGalben1, LOW);
    delay(200);
  }
}
